(() => {
  const $=id=>document.getElementById(id),n=x=>Number(x||0).toLocaleString(),esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state=null,busy=false;
  const hours=seconds=>seconds==null?'Measuring…':seconds<3600?Math.ceil(seconds/60)+' min':(seconds/3600).toFixed(1)+' hours';
  async function action(kind,extra={}){
    if(busy)return;busy=true;
    try{const r=await fetch('campaign/action',{method:'POST',headers:{'Content-Type':'application/json','X-Campaign-Control':'1'},body:JSON.stringify({action:kind,id:state?.id,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error||'Action failed');$('campaign-message').textContent=kind==='pause'?'Pause requested. The current scenario will finish.':kind==='replay'?'Diagnostic replay requested. Its report and waveform will appear in the campaign replays folder.':'Worker requested. Progress appears as it starts.';}
    catch(e){$('campaign-message').textContent=e.message;}finally{busy=false;poll();}
  }
  function draw(){
    const running=['running','qualifying','measuring'].includes(state.status),acceptance=state.kind==='acceptance';
    $('campaign-status').textContent=(acceptance?'Acceptance test · ':'')+state.status.replaceAll('-',' ');
    $('campaign-start').disabled=running||(!acceptance&&!!state.id&&!state.source_changed);
    $('campaign-pause').disabled=!running;
    $('campaign-resume').disabled=!state.id||running||['completed','behavioral-complete','stopped'].includes(state.status);
    const committed=state.checked||0,target=state.target||10000000;
    $('campaign-progress').max=target;$('campaign-progress').value=committed;
    const inflight=state.in_flight?.checked||0;
    const flightLabel=state.status==='qualifying'?'qualification cases · outside the campaign budget':'in flight · excluded until batch commits';
    $('campaign-numbers').innerHTML=`<div><span>Committed checks</span><strong>${n(committed)} / ${n(target)}</strong></div><div><span>Current work</span><strong>${esc(state.current_candidate?state.current_candidate+' · '+(state.phase||state.stage||''):'Ready')}</strong><small>${n(inflight)} ${flightLabel}</small></div><div><span>Measured remaining time</span><strong>${hours(state.eta_seconds)}</strong><small>${state.checks_per_second?state.checks_per_second.toFixed(1)+' checks/s · simulation only':'Qualification and physical builds are separate'}</small></div>`;
    $('campaign-stages').innerHTML=Object.entries(state.stages||{}).map(([s,budget])=>{const done=Object.values(state.by_stage?.[s]||{}).reduce((a,b)=>a+b,0);return `<div><span>${esc(s)} · ${n(done)} / ${n(budget)}</span><progress value="${done}" max="${budget}" aria-label="${s} checks"></progress></div>`;}).join('');
    const root=state.id?'../results/campaigns/'+encodeURIComponent(state.id)+'/':'';
    const audit=state.ledger_audit;
    $('campaign-audit').innerHTML=audit?.status==='passed'?`<a href="${root}ledger-audit.json" target="_blank" rel="noopener">Ledger audit</a> · ${n(audit.checked)} committed checks verified · ${audit.budget_complete?'budget complete':'partial snapshot'} · ${esc(new Date(audit.audited_at*1000).toLocaleString())}`:'Ledger audit: not recorded for this revision yet.';
    $('campaign-manifest').hidden=!state.id;if(state.id)$('campaign-manifest').href=root+'manifest.json';
    const candidates=Object.entries(state.candidates||{});
    $('campaign-designs').innerHTML=candidates.length?`<div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Correctness</th><th>Mapped area</th><th>Physical result</th></tr></thead><tbody>${candidates.map(([id,c])=>{const t=state.by_candidate?.[id]||{},m=c.hardware?.mapping||{},p=c.hardware?.physical||{};return `<tr><td><strong>${id} · ${esc(c.label)}</strong><small>${c.words} words · ${c.fused?'SHIFTWAIT':'7 instructions'} · UART ${c.uart_words} words</small><small>${c.load_clocks} byte-loading clocks</small>${c.qualification==='passed'?'<details><summary>Verified UART completion</summary>From accepted START to completion: 10 × bit duration + 2 clocks. For durations 3, 4, 8, 17, 31, 80, 255, 256, 4095 and 4096, directed checks verify completion at 32, 42, 82, 172, 312, 802, 2552, 2562, 40952 and 40962 clocks.</details>':''}</td><td>${t.failed?'Disqualified':esc(c.qualification)}<small>${n(t.checked)} checked · ${n(t.failed)} failures</small><a href="${root}candidates/${id}/qualification.json" target="_blank">Qualification</a></td><td>${m.status==='passed'?n(m.area_um2)+' µm²':'Not measured'}<small>${m.cells?n(m.cells)+' cells':''}</small></td><td>${esc(p.status||'Not measured')}<small>${esc(p.area_um2==null?'Routed area unavailable':n(p.area_um2)+' µm²')} · setup ${esc(p.setup_slack_ns==null?'unverified':p.setup_slack_ns+' ns')} · hold ${esc(p.hold_slack_ns==null?'unverified':p.hold_slack_ns+' ns')}</small>${p.blockers?.length?`<details><summary>Blocker</summary>${esc(p.blockers.join('. '))}</details>`:''}</td></tr>`;}).join('')}</tbody></table></div>`:'';
    $('campaign-ranking').textContent=(state.ranking?.length?'Leaders: '+state.ranking.join(' → ')+' · '+state.ranking_basis+'. ':'')+(state.reason||'')+(state.source_changed?' Source files changed; this campaign continues using its frozen snapshot.':'');
    $('campaign-coverage').innerHTML=candidates.map(([id])=>{const c=state.by_candidate?.[id]?.coverage||{},bytes=Object.keys(c).filter(k=>k.startsWith('byte:')).length,durations=Object.keys(c).filter(k=>k.startsWith('duration:')).length,controls=Object.keys(c).filter(k=>k.startsWith('control:')).length,bounds=Object.keys(c).filter(k=>k.startsWith('boundary:')).length;return `<p class="caption"><strong>${id}</strong> · payload bins ${bytes}/256 · bulk durations ${durations}/6 · controls ${controls}/7 · boundaries ${bounds}/8. Scenarios: UART ${n(c.uart)}, pulse ${n(c.pulse)}, control ${n(c.control)}, boundary ${n(c.boundary)}.</p>`;}).join('');
    $('campaign-failures').innerHTML=(state.failures||[]).map((f,i)=>`<p><a target="_blank" href="${root}${esc(f.evidence)}">${esc(f.candidate)} · ${esc(f.stage)} · case ${f.case_id} · seed ${f.seed}</a><br><small>Revision ${esc(state.revision?.slice(0,12))} · <a target="_blank" href="${root}candidates/${esc(f.candidate)}/project.v">Frozen design</a></small>${esc(f.message)} <button data-replay="${i}" ${running?'disabled':''}>Replay with waveform</button> <a target="_blank" href="${root}replays/${esc(f.stage)}-${esc(f.candidate)}-${f.case_id}/report.json">Replay report</a></p>`).join('')||'<p class="caption">No failing campaign scenarios recorded. Qualification and mutation checks are available separately above.</p>';
    $('campaign-failures').querySelectorAll('button').forEach(b=>b.onclick=()=>{const f=state.failures[Number(b.dataset.replay)];action('replay',{candidate:f.candidate,stage:f.stage,case_id:f.case_id});});
    window.CHIPWHEEL_CAMPAIGN=state.id?{id:state.id,revision:state.revision,checked:state.checked,baseline_rtl_sha256:state.candidates?.A?.rtl_sha256}:null;
  }
  async function poll(){try{const r=await fetch('campaign.json',{cache:'no-store'});if(!r.ok)throw Error();state=await r.json();draw();}catch{$('campaign-status').textContent='Campaign connection unavailable';}}
  $('campaign-start').onclick=()=>action('start');$('campaign-pause').onclick=()=>action('pause');$('campaign-resume').onclick=()=>action('resume');poll();setInterval(poll,3000);
})();
