#!/usr/bin/env python3
"""Incumbent comparison: same-flow area/timing x measured protocol speed.

Inputs (all regenerated by their own scripts):
  results/arena/<name>/arena.json  scripts/arena.py (area + pre-layout STA)
  incumbents/results.json          incumbents/run_all.py (incumbent cycle counts)
  v2/results/workloads.json        v2/test/workloads.py (Chipwheel v2 cycle counts)

Speed = sustained payload bits per clock (8 / clocks-per-byte, fastest correct
setting, measured in simulation with data checked at the pins). Size = mapped
cell area. Density = bits/clock per mm^2. All ratios are at an EQUAL clock,
which is the conservative comparison (Tiny Tapeout I/O, not logic, limits the
clock of every design here). Writes results/benchmark.json and prints Markdown.

    python3 scripts/compare.py [--v2 CW2_r5]
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# v1 UART: acceptance-to-completion 2+10B clocks at its minimum B=3, plus one
# edge before the next START can be accepted (docs/spec.md). One byte per START.
V1_UART_CPB = 2 + 10 * 3 + 1


def arena(name):
    return json.loads((ROOT / 'results/arena' / name / 'arena.json').read_text())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--v2', default='CW2_r5')
    a = ap.parse_args()
    wl = json.loads((ROOT / 'v2/results/workloads.json').read_text())
    inc = {r['name']: r for r in json.loads((ROOT / 'incumbents/results.json').read_text())}

    def row(label, arena_name, uart, spi, uprog, sprog, note=''):
        r = arena(arena_name)
        t = r['timing']
        return {'design': label, 'arena': arena_name, 'area_um2': r['area_um2'],
                'area_with_repair_bufs_um2': r['area_um2'] + t.get('repair_buffer_area_um2', 0.0),
                'flops': r['flops'], 'latches': r['latches'], 'fmax_mhz_prelayout': t['fmax_mhz_reg2reg'],
                'uart_clocks_per_byte': uart, 'spi_clocks_per_byte': spi,
                'uart_program_bits': uprog, 'spi_program_bits': sprog, 'note': note}

    rows = [row('Chipwheel v2', a.v2, wl['uart_tx']['clocks_per_byte_sustained'],
                wl['spi_mode0']['clocks_per_byte_sustained'], wl['uart_tx']['program_bits'],
                wl['spi_mode0']['program_bits'], '10x8 latch program + 3 config words'),
            row('Chipwheel v1', 'A_v1', V1_UART_CPB, None, 9 * 16, None, '32x16 flop program, UART TX only')]
    for name, label in [('pio_sm1', 'PIO-class, 1 SM (fpga_pio)'), ('femtorv_bb', 'FemtoRV32 bit-bang'),
                        ('qerv_bb', 'QERV bit-bang'), ('serv_bb', 'SERV bit-bang'),
                        ('pio_full', 'PIO-class, 4 SMs (fpga_pio)')]:
        r = inc[name]
        rows.append(row(label, 'INC_' + name, r['uart_tx']['clocks_per_byte_sustained'],
                        r['spi_mode0']['clocks_per_byte_sustained'], r['uart_tx']['program_bits'],
                        r['spi_mode0']['program_bits']))
    v2 = rows[0]
    for r in rows:
        r['area_ratio'] = r['area_um2'] / v2['area_um2']
        r['area_ratio_with_bufs'] = r['area_with_repair_bufs_um2'] / v2['area_with_repair_bufs_um2']
        r['uart_speed_ratio'] = r['uart_clocks_per_byte'] / v2['uart_clocks_per_byte']
        r['spi_speed_ratio'] = (r['spi_clocks_per_byte'] / v2['spi_clocks_per_byte']) if r['spi_clocks_per_byte'] else None
        r['uart_density_ratio'] = r['area_ratio'] * r['uart_speed_ratio']
        r['spi_density_ratio'] = r['area_ratio'] * r['spi_speed_ratio'] if r['spi_speed_ratio'] else None
    out = {'v2': a.v2, 'basis': 'equal clock; mapped cell area (CMOS5L typ, Yosys/ABC); pre-layout STA',
           'v1_as_specified': {'v1_clock_mhz': 10, 'v2_clock_mhz': 50,
                               'speed_ratio': 50 / 10 * V1_UART_CPB / v2['uart_clocks_per_byte'],
                               'density_ratio': 50 / 10 * V1_UART_CPB / v2['uart_clocks_per_byte'] * rows[1]['area_ratio']},
           'rows': rows}
    (ROOT / 'results/benchmark.json').write_text(json.dumps(out, indent=1))

    def f(x, d=1):
        return '—' if x is None else f'{x:,.{d}f}'
    print('| Design | Cell area µm² | fmax* MHz | UART clk/byte | SPI clk/byte | v2 smaller by | v2 faster (UART / SPI) | v2 bits/clk/mm² advantage (UART / SPI) |')
    print('|---|---:|---:|---:|---:|---:|---:|---:|')
    for r in rows:
        print(f"| {r['design']} | {r['area_um2']:,.0f} | {r['fmax_mhz_prelayout']:.0f} | {f(r['uart_clocks_per_byte'], 0)} | "
              f"{f(r['spi_clocks_per_byte'], 0) if r['spi_clocks_per_byte'] else 'unsupported'} | {r['area_ratio']:.1f}x | "
              f"{r['uart_speed_ratio']:.1f}x / {f(r['spi_speed_ratio']) + 'x' if r['spi_speed_ratio'] else '∞'} | "
              f"{r['uart_density_ratio']:.1f}x / {f(r['spi_density_ratio']) + 'x' if r['spi_density_ratio'] else '∞'} |")
    s = out['v1_as_specified']
    print(f"\n*pre-layout NLDM STA, typical corner. v1 as specified (10 MHz) vs v2 at 50 MHz: "
          f"{s['speed_ratio']:.1f}x UART throughput, {s['density_ratio']:.1f}x throughput per area.")


if __name__ == '__main__':
    main()
